/**
 * GENERATED by scripts/build-brand-assets.mjs from the --bot-* tokens in
 * src/app/globals.css. Don't edit by hand; change the tokens and re-run.
 *
 * The light-theme values only. OG images and downloadable bot files are always
 * drawn on paper, and neither Satori nor a downloaded SVG can resolve a CSS
 * variable, so they need the colours as literals.
 *
 * This is the one file DESIGN.md §1's hue check exempts from the raw-hex rule.
 */
import type { Palette } from "@/lib/bot-geometry";

export type BotPalette = Palette & { ink: string; tint: string };

export const BOT_PALETTE: Record<string, BotPalette> = {
  graphite: { disc: "#2b2b2b", ring: "transparent", faceInk: "#ffffff", ink: "#2b2b2b", tint: "#e1e1e1" },
  coral: { disc: "#f2644a", ring: "transparent", faceInk: "#141414", ink: "#b93a22", tint: "#fde9e6" },
  amber: { disc: "#f0a524", ring: "rgb(10 10 10 / 0.12)", faceInk: "#141414", ink: "#8f5a00", tint: "#fdf2e0" },
  lime: { disc: "#7cc639", ring: "rgb(10 10 10 / 0.12)", faceInk: "#141414", ink: "#3f7a12", tint: "#edf7e3" },
  teal: { disc: "#1fb5a6", ring: "rgb(10 10 10 / 0.12)", faceInk: "#141414", ink: "#0b7166", tint: "#e0f5f3" },
  sky: { disc: "#3b9eff", ring: "rgb(10 10 10 / 0.12)", faceInk: "#141414", ink: "#1464c0", tint: "#e4f1ff" },
  violet: { disc: "#8b6cf6", ring: "transparent", faceInk: "#141414", ink: "#5b3fd1", tint: "#efeafe" },
  pink: { disc: "#ef5da8", ring: "transparent", faceInk: "#141414", ink: "#b52a73", tint: "#fde8f3" },
};

/** A bot colour's palette, falling back to graphite. */
export const paletteFor = (color: string): BotPalette =>
  BOT_PALETTE[color] ?? BOT_PALETTE.graphite;
